### ISSUE TITLE
Retrieving full resources from included based on relationship resource identifiers

### ISSUE THREAD

**Issue by sonjapeterson** [beauby/jsonapi#21]
One thing I often need to do with JSONAPI documents is to take a resource identifier from a relationship in the main `data` section and find the linked full resource from `included`. I end up writing a lot of code (or having to define my own helper for) things like: 
```
identifier = document.data.relationships.default_payment_method.data
document.included.find{|x| identifier.id == x.id && identifier.type == x.type }
```
So I was wondering if you'd be open to a PR that adds something like this:
```
document.find_included(document.data.relationships.payment_method.data)
```
`find_included` would take a resource identifier and retrieve the resource from included for you--could either just iterate through full array to find it or we could set up a more efficient data structure for retrieval when we initialize the document. This way you could give any resource identifier to the document--including ones from a different document, or from another resource in included--and try to retrieve it from included. It's a small thing but I think it would be useful.

Another option would be to optionally link relationships to full resources when initializing the document, so you could call a method like `full_resource` on any instance of `JSONAPI::Relationship`. Could get into odd recursive nesting situations with that though, so maybe the first method is enough.

Let me know what you think!

**Comment by beauby** [comment]
Hi Sonja,

You are right that currently this gem does not handle linking relationships with the included resources. The aim of this project is mainly to validate JSON API payloads, not really to become a full client, although it could make sense to do the linking. I'll work on a PR. 
In the meantime, I suggest you do something like the following, to avoid traversing the whole `included` array upon each lookup:
```ruby
included = Hash[document.included.map { |res| [[res.id, res.type], res] }]
# then you can do
included[relationship.data]
```

**Comment by beauby** [comment]
ref #24.

**Comment by beauby** [comment]
Closing this, as it is a client concern, so this feature will not be implemented. Feel free to add comments if you need help solving your problem, or want to share a solution for others.

**Comment by Rio517** [comment]
That's a shame.  I feel like this is pretty fundamental to the JSON-API spec.  Without this feature, this seems like a fairly incomplete parser.

I've looked around for lightweight client libraries that might provide the layer I need.  Are you referencing any clients in particular that you could point out? Thanks!

P.S. Thanks for all the hard work on this project, generally.

**Comment by beauby** [comment]
@Rio517 Thanks! You are right that it is. However, this gem is intended to be a server-side gem, and from a server-side perspective, one never receives general documents with `included` resources, but only resource update/creation and relationship update payloads, for which it makes more sense to use some domain-specific validation library (like [https://github.com/beauby/jsonapi-validations](jsonapi-validations)), or some mapping library that creates domain-specific hashes from JSONAPI payloads (like [https://github.com/beauby/jsonapi-deserializable](jsonapi-deserializable)).

I do not personally know (but I have never needed it either...) of any low-level ruby JSONAPI client, but if you have ideas what it may look like I suggest you start something and post a link here – I'd gladly help.
