### ISSUE TITLE
JSONAPI::Resource clashes with the jsonapi-resources gem

### ISSUE THREAD

**Issue by timabdulla** [beauby/jsonapi#26]
If you have both the `jsonapi` gem and the `jsonapi-resources` gem, there is a conflict as both gems define the `JSONAPI::Resource` class. This conflict did not exist until this gem moved to the `JSONAPI` namespace. The only solution to me seems to be that both gems use independent namespaces.

**Comment by beauby** [comment]
This is indeed an issue, although arguably at this stage JR and jsonapi should probably not be used together. Could you outline your usecase so that I have a better understanding of the situation?

**Comment by timabdulla** [comment]
@beauby I use the `jsonapi` gem for parsing responses in my acceptance tests in a project that uses `jsonapi-resources` to serve those responses. :)

**Comment by anothermh** [comment]
@beauby I use `jsonapi` to consume a finicky JSONAPI service, and use `jsonapi-resources` to provide my own JSONAPI-compliant API. There's tons of potential for overlap between these two libraries and I would also like to see a solution for it.

**Comment by beauby** [comment]
With the last PR, the code for the parser has moved under the `JSONAPI::Parser` namespace (except for the main function that remains `JSONAPI.parse`), so the `jsonapi-resources` clash should be sorted. Could any of you try? (The new version of the gem has not ben released, so you'd need to tap from git directly).

**Comment by beauby** [comment]
Closing this as I believe it is sorted now (feel free to reopen if needed).
