### ISSUE TITLE
undescriptive error on nil input

### ISSUE THREAD

**Issue by NullVoxPopuli** [beauby/jsonapi#35]
`no implicit conversion of nil into String"`

it should be InvalidDocument, yeah? -- or something more descriptive?

**Comment by beauby** [comment]
Agreed, it is just a matter of adding proper logic [here](https://github.com/beauby/jsonapi/blob/master/lib/jsonapi/parse.rb#L14). Feel free to issue a PR, or I'll do it in October when I have more time!

**Comment by NullVoxPopuli** [comment]
@beauby https://github.com/beauby/jsonapi/pull/37
