### ISSUE TITLE
cannot load jsonapi file from active_support/dependencies.rb

### ISSUE THREAD

**Issue by vitor-caetano** [beauby/jsonapi#44]
Hi, I'm getting this:

activesupport-4.1.14.1/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- jsonapi (LoadError)

since the update for 0.1.1.beta4

Yes, I do use version 4.1.14.1 for activesupport.

Hope this helps.. Thanks for the good job!

**Comment by beauby** [comment]
This is failing for the same reason as #45. I just pushed a new (fixed) version.
