### ISSUE TITLE
I think there's an incorrect assertion in `Document#parse_resource_identifier!`

### ISSUE THREAD

**Issue by diminish7** [beauby/jsonapi#46]
This assertion here: https://github.com/beauby/jsonapi/blob/master/parser/lib/jsonapi/parser/document.rb#L126

That assertion currently fails when the resource identifier has both `id` and `type`.
Based on what the error message is, I think it should test for equality rather than inequality:
```ruby
ensure!(ri.keys & RESOURCE_IDENTIFIER_KEYS == RESOURCE_IDENTIFIER_KEYS,
                'A resource identifier object MUST contain ' \
                "#{RESOURCE_IDENTIFIER_KEYS} members.")
```

**Comment by beauby** [comment]
You are right indeed. I initially expressed all the negated conditions and that one creeped through the change. Would you mind issuing a PR for fixing that? If not, I'll do it over the weekend.
Thanks for reporting it!

**Comment by diminish7** [comment]
Yep, will do! (Probably tomorrow-ish)

**Comment by diminish7** [comment]
@beauby PR'd (#48) Thanks!

**Comment by beauby** [comment]
Thanks a lot @diminish7 – will review it tonight!
