### ISSUE TITLE
Should the "parser" be a "validator"?

### ISSUE THREAD

**Issue by diminish7** [beauby/jsonapi#47]
I'm in the middle of upgrading from `beta2` to `beta5`, and it seems like parsing is no longer a part of this gem's functionality. I spent a bit of time trying to figure out why the result of `parse!` was always `nil`. By the time it gets to the "parser" now, it is expected to already by parsed, and the core functionality here seems to be to raise an exception if the already-parsed object doesn't match JSON API expectations.

**Comment by beauby** [comment]
You are totally right that there was a decision to move away from the "parsing into an object graph" mentality. The rationale being that 1. validating a JSONAPI document should not imply creating a bunch of objects (for perfs/GC reasons), and 2. once the validation has happened, the hash can be safely accessed, and building objects on top adds little value in my opinion (but I'd like to hear yours).
As for keeping the name parser, it seemed somewhat consistent with the fact that a parser, in general, is a tool that does syntaxical analysis, which this tool does, although it usually implies that the document is being transformed into a given structure, which does not happen here anymore.

**Comment by diminish7** [comment]
Cool, fair enough, thanks for the response!
