### ISSUE TITLE
It can't parse the post request for jsonapi data/resource(s)

### ISSUE THREAD

**Issue by smartepsh** [beauby/jsonapi#49]
At jsonapi.org--[create a resource by jsonapi](http://jsonapi.org/format/#crud-creating), the request does not have 'id' field. For example,
```ruby
document = {
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}

JSONAPI.parse_resouce!(document)
```
It just return `JSONAPI::Parser::InvalidDocument: The request MUST include a single resource object as primary data.` 

So can any one add this parser?

PS: Base on the jsonapi standard , I usually do some batch_operation by pull the request like
```json
{
  "data": {
    "type": "photos",
    "attributes": [{
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },{
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },{
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    }]
  }
}
```
So I hope this gem can also parse data to hash array.

**Comment by beauby** [comment]
Regarding your first example, it is expected to work (when using `parser_resource` the `id` of the primary resource is not required).
Your problem comes from the fact you're using `"key": value` where ruby (at least version 2.0) expects `"key" => value` for hashes with string keys.

**Comment by beauby** [comment]
In more recent rubies, the syntax `"key": value` is valid, although it transforms the key into a symbol, which causes the parser to fail (as incoming payloads always have string keys).
Closing this, but feel free to keep commenting if you have more questions/need help.
