### ISSUE TITLE
Yanked beta2 gem version breaks activemodel-serializers release 0.10.2

### ISSUE THREAD

**Issue by Nitrodist** [beauby/jsonapi#50]
Activemodel-serializers is currently broken due to the gem being yanked from rubygems.org. Failure indicates like this:

```
  + bundle install
  Fetching gem metadata from https://rubygems.org/
  Fetching version metadata from https://rubygems.org/
  Fetching dependency metadata from https://rubygems.org/
  Could not find jsonapi-parser-0.1.1.beta2 in any of the sources (Executor::NonZeroExitStatus)
```

If we can unyank the gem, that would fix this issue. The twiddle-wakka (~>) used in AMS's gemspec does not automatically increment to beta3, unfortunately.

**Comment by beauby** [comment]
I already opened a ticket on RubyGems to unyank it.
I'm not sure exactly what's happening though, as `jsonapi` v0.1.1.beta2 did not depend on `jsonapi-parser`.

**Comment by beauby** [comment]
Ok so, as it turns out, `~> 0.1.1.beta2` is being resolved to `0.1.1.beta6`, which means the bundler error should disappear as soon as the right caches get updated. 
I relaunched a build on AMS's Travis, it's green. Could you confirm this is still an issue @Nitrodist?

**Comment by beauby** [comment]
Update: I just built a vanilla rails app with `gem 'active_model_serializers', '~> 0.10.2'` and all went fine.

**Comment by Nitrodist** [comment]
Sorry, I was referring to the jsonapi-parser gem beta2 gem being yanked.

Here's what is in my Gemfile.lock:

```
    jsonapi (0.1.1.beta5)
      jsonapi-parser (= 0.1.1.beta2)
      jsonapi-renderer (= 0.1.1.beta1)
```

Every beta version you just yanked should be put back in, in my opinion.

The reason why the current version works is because it depends on the latest beta versions. Users like myself that installed AMS with version 0.10.2 when the latest beta was at '5' (beta5) will see the error.

**Comment by beauby** [comment]
Just run `$ bundle update`, that should solve your issue (It will resolve `jsonapi` to `jsonapi v0.1.1.beta6`). Or if updating your whole gem set is not an option, updating the Gemfile.lock will do. 
At the time of AMS 0.10.2 release, the latest version was `jsonapi v0.1.1.beta2`.

**Comment by Nitrodist** [comment]
That is OK advice, but really, you shouldn't be yanking gems because you're breaking deployments.

Anyone who had followed AMS's advice and used 0.10.2 in production because it was considered 'generally safe and recommended' according to the README now either has to do as you say or change their Gemfile to point to the beta release via github. 

A similar issue happened with the mime-types 2.4.2 release and Austin Ziegler ended up unyanking the release because you're effectively forcing everyone to upgrade or downgrade despite the code working fine for them. [This Stackoverflow post](http://stackoverflow.com/questions/26492800/could-not-find-mime-types-2-4-2-in-any-of-the-sources) talks about it a bit.

**Comment by beauby** [comment]
Yeah I agree, yanking was not the right move here. However, I expected AMS to be relying on a specific version (i.e. 0.1.1.beta2) of this gem, as it is still in beta and semantic versioning does apply to pre-1.0 versions.
For anyone ending up here: `$ bundle update` will solve the issue, manually editing the `Gemfile.lock` to set `jsonapi` version to `0.1.1.beta6` will solve it as well.
